// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrzlesiydehwdygukmyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yemxlc2l5ZGVod2R5Z3VrbXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODY3MTUsImV4cCI6MjA1OTA2MjcxNX0.mZAGQabzP5U87lSZ1FbCSgzavNwYtXZISpYp1IeV4b4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);